---
title: "Saint Egbert School and Parish Music Ministry"
subtitle: "December 13, 2025 | 7:00 PM"
---

### Overview

This site outlines a **draft** program for a proposed **Advent Festival Lessons, Carols, and Pageantry** that combines a traditional Advent Lessons and Carols, popularized by [King's College in Cambridge](https://www.youtube.com/watch?v=j9Tz1QgRs5Y), with St. Egbert School's traditional Christmas pageant. This is merely a starting point to consider and, possibly, for us to build upon and iterate through.

Presumably this would take place some evening in Advent, like the pageant. Date and time TBD pending approval.

### Integrating the Christmas Pageant

It currently contains nine readings (which is customary, but could be reduced to 7 if needed) and proposed songs for each. Pageant scenes can be plugged in wherever they align with the lessons, presumably starting around Lessons 4, 5, or 6. The Christmas song [O Come, Little Children](https://www.youtube.com/watch?v=v4ZkfUAiGCM) could be sung at whatever lesson contains their first acting scene--or the lesson immediately before that--as they move into place. (It's currently scheduled at Lesson 6 but this could be too late in the line up.) Kids singing in chorus/choir can be included from the very beginning or sporadically throughout.

Presumably the readings could replace pageant narrations and silent acting scenes could be performed while the corresponding song is being sung. Any scenes with spoken parts would probably be most appropriate after the reading and before the song. To be determined.

### A note on music

Lessons and Carols is a lot of music, as the name implies, but with one or two exceptions, all songs and hymns here are familiar to the parish/choir. [Mary, Did You Know](https://www.youtube.com/watch?v=F1H1-scfD1s) was included upon request from the kids. We will need to purchase this if we use it.

The vision is to include the Parish Choir (with regular evening rehearsals between now and December), school chorus (weekly practice during the school day), any kids from the parish who do not attend the school (considering a regular practice on Sunday mornings), and instrumentalists (band members from last year plus new members, possibly Hispanic musicians if interested, with weekly rehearsals between now and December). In the future, if we opt to go this route, we could also use this as an opportunity to stand up and integrate a St. Egbert School Alumni Choir and also extend invitations to musicians in neighboring parishes.

There are obviously many popular and familiar Christmas carols from which to choose. We can substitute with some that the kids might be more familiar with this year, if needed, given the timeframe and how this would already be a change.

**Use the side bar or the navigation links at the bottom of each page to review the outline.**