---
title: Seventh Lesson
subtitle: Visit of the Magi [Matthew 2:1-12]{style="float:right" .small}
---

## Lesson 

When Jesus was born in Bethlehem of Judea, in the days of King Herod, behold, magi from the east arrived in Jerusalem,
saying, “Where is the newborn king of the Jews? We saw his star at its rising and have come to do him homage.”
When King Herod heard this, he was greatly troubled, and all Jerusalem with him.
Assembling all the chief priests and the scribes of the people, he inquired of them where the Messiah was to be born.
b They said to him, “In Bethlehem of Judea, for thus it has been written through the prophet:

‘And you, Bethlehem, land of Judah,  
are by no means least among the rulers of Judah;  
since from you shall come a ruler,  
who is to shepherd my people Israel.’”  

Then Herod called the magi secretly and ascertained from them the time of the star’s appearance.
He sent them to Bethlehem and said, “Go and search diligently for the child. When you have found him, bring me word, that I too may go and do him homage.”
After their audience with the king they set out. And behold, the star that they had seen at its rising preceded them, until it came and stopped over the place where the child was.
They were overjoyed at seeing the star,
and on entering the house they saw the child with Mary his mother. They prostrated themselves and did him homage. Then they opened their treasures and offered him gifts of gold, frankincense, and myrrh.
And having been warned in a dream not to return to Herod, they departed for their country by another way.

## Carol

#### O Come, All Ye Faithful [ADESTE FIDELES]{style="float:right" .small}

{{< video https://www.youtube.com/watch?v=H2xzRghgpR0 >}}

Full choirs plus congregation

## Prayer

Lord,  
you are the giver of all good gifts.  
May we always remember to share our gifts with others  
for the glory of your name.  
Amen.