---
title: Third Lesson
subtitle: '**Davidic King:** *With righteousness he shall judge the poor.* [Isaiah 11:1-10]{style="float:right" .small}'
---

## Lesson

A reading from the book of the prophet Isaiah.

On that day:  
A shoot shall come out from the stump of Jesse,  
and a branch shall grow out of his roots.  
The spirit of the Lord shall rest on him,  
the spirit of wisdom and understanding,  
the spirit of counsel and might,  
the spirit of knowledge and the fear of the Lord.  
His delight shall be in the fear of the Lord.  

He shall not judge by what his eyes see,  
or decide by what his ears hear;  
but with righteousness he shall judge the poor,  
and decide with equity for the meek of the earth;  
he shall strike the earth with the rod of his mouth,  
and with the breath of his lips he shall kill the wicked.  
Righteousness shall be the belt around his waist,  
and faithfulness the belt around his loins.  

The wolf shall live with the lamb,  
the leopard shall lie down with the kid,  
the calf and the lion and the fatling together,  
and a little child shall lead them.  
The cow and the bear shall graze,  
their young shall lie down together;  
and the lion shall eat straw like the ox.  
The nursing child shall play over the hole of the asp,  
and the weaned child shall put its hand on the adder’s den.  
They will not hurt or destroy  
on all my holy mountain;  
for the earth will be full of the knowledge of the Lord  
as the waters cover the sea.  

On that day the root of Jesse shall stand  
as a signal to the peoples;  
the nations shall inquire of him,  
and his dwelling shall be glorious.

The word of the Lord.

## Carol

#### People, Look East [BESAN&#x00C7;ON]{style="float:right" .small}

{{< video https://www.youtube.com/watch?v=YGjPQ5yitcM >}}

## Prayer

Lord,  
we wait for the day of your peace.  
May we help to bring this peace  
in our families, our communities, and our world.  
We ask this through Christ our Lord.  
Amen.

### Estimated time

**This lesson:** 5 min [**Total: 25 min** ]{style="float:right" .small}