---
title: Second Lesson
subtitle: '**Promise of Salvation:** *Make straight in the desert a highway for our God.* [Isaiah 40:1-5, 9-11]{style="float:right" .small}'
---

## Lesson

A reading from the book of the prophet Isaiah.

Comfort, O comfort my people,  
says your God.  
Speak tenderly to Jerusalem,  
and cry to her  
that she has served her term,  
that her penalty is paid,  
that she has received from the Lord’s hand  
double for all her sins.  

A voice cries out:  
“In the wilderness prepare the way of the Lord,  
make straight in the desert a highway for our God.  
Every valley shall be lifted up,  
and every mountain and hill be made low;  
the uneven ground shall become level,  
and the rough places a plain.  
Then the glory of the Lord shall be revealed,  
and all people shall see it together,  
for the mouth of the Lord has spoken.”  

Get you up to a high mountain,  
O Zion, herald of good tidings;  
lift up your voice with strength,  
O Jerusalem, herald of good tidings,  
lift it up, do not fear;  
say to the cities of Judah,  
“Here is your God!”  

See, the Lord God comes with might,  
and his arm rules for him;  
his reward is with him,  
and his recompense before him.  

He will feed his flock like a shepherd;  
he will gather the lambs in his arms,  
and carry them in his bosom,  
and gently lead the mother sheep.  

The word of the Lord.

## Carol 

#### Comfort, Comfort, O My People [GENEVAN 42]{style="float:right" .small}

{{< video https://www.youtube.com/watch?v=hrvXny0h_tw&list=RDhrvXny0h_tw&start_radio=1 >}}

## Prayer


### Estimated time

**This lesson:** 4 min [**Total: 20 min** ]{style="float:right" .small}