---
title: Fourth Lesson
subtitle: '**The Announcement of the Birth of Jesus:** *You will conceive in your womb and bear a son.* [Luke 1:26-38]{style="float:right" .small}'
---

## Lesson

A reading from gospel according to Luke.

In the sixth month the angel Gabriel was sent by God  
to a town in Galilee called Nazareth,  
to a virgin engaged to a man whose name was Joseph,  
of the house of David.  
The virgin’s name was Mary.  

And the angel came to Mary and said,  
“Greetings, favored one! The Lord is with you.”  
But she was much perplexed by his words  
and pondered what sort of greeting this might be.  

The angel said to her,  
“Do not be afraid, Mary,  
for you have found favor with God.  
And now, you will conceive in your womb and bear a son,  
and you will name him Jesus.  

“He will be great,  
and will be called the Son of the Most High,  
and the Lord God will give to him the throne of his ancestor David.  
He will reign over the house of Jacob forever,  
and of his kingdom there will be no end.”  

Mary said to the angel,  
“How can this be, since I am a virgin?”  
The angel said to her,  
“The Holy Spirit will come upon you,  
and the power of the Most High will overshadow you;  
therefore the child to be born will be holy;  
he will be called Son of God.  

“And now,  
your relative Elizabeth in her old age has also conceived a son;  
and this is the sixth month for her who was said to be barren.  
For nothing will be impossible with God.”  
Then Mary said,  
“Here am I, the servant of the Lord;  
let it be with me according to your word.”  
Then the angel departed from her.  

The word of the Lord.

## Carol

#### The Angel Gabriel from Heaven Came [GABRIEL'S MESSAGE]{style="float:right" .small}

{{< video https://www.youtube.com/watch?v=L-Rv-J46gvM >}}

## Prayer

Lord,  
you asked Joseph and Mary to trust in you.  
May we come to share in their trust  
and always rely on you.  
We ask this through Christ our Lord.  
Amen.

### Estimated time

**This lesson:** 5 min [**Total: 30 min** ]{style="float:right" .small}