---
title: Sixth Lesson
subtitle: '**The Birth of Jesus:** *To you is born this day a Savior, who is the Messiah.* [Luke 2:8-20]{style="float:right" .small}'
---

## Lesson

A reading from the gospel according to Luke.

In that region there were shepherds living in the fields,  
keeping watch over their flock by night.  
Then an angel of the Lord stood before them,  
and the glory of the Lord shone around them,  
and they were terrified.  
But the angel said to them,  
“Do not be afraid; for see—  
I am bringing you good news of great joy for all the people:  
to you is born this day in the city of David a Savior,  
who is the Messiah, the Lord.  
This will be a sign for you:  
you will find a child wrapped in bands of cloth  
and lying in a manger.”  

And suddenly there was with the angel  
a multitude of the heavenly host,  
praising God and saying,  
“Glory to God in the highest heaven,  
and on earth peace among those whom he favors!”

When the angels had left them and gone into heaven,
the shepherds said to one another,
“Let us go now to Bethlehem
and see this thing that has taken place,
which the Lord has made known to us.”

So they went with haste and found Mary and Joseph,
and the child lying in the manger.
When they saw this,  
they made known what had been told them about this child;  
and all who heard it were amazed  
at what the shepherds told them.  

But Mary treasured all these words  
and pondered them in her heart.  
The shepherds returned, glorifying and praising God. 
for all they had heard and seen,  
as it had been told them.  

The word of the Lord.


## Carol

#### 1. Hark! the Herald Angels Sing [MENDELSSOHN]{style="float:right" .small}

{{< video https://www.youtube.com/watch?v=kZQGgpqQhs4 >}}

Full choirs and congregation; transition to Christmas music

#### 2. O Come, Little Children [IHR KINDERLEIN, KOMMET]{style="float:right" .small}

{{< video https://www.youtube.com/watch?v=v4ZkfUAiGCM >}}

Pageant participants move into place during this song.

::: {.callout-note}
If the pageant has scenes prior to the birth of Jesus, this song can be moved earlier in the program.
:::

## Prayer

Lord,  
you came to us in humility and vulnerability.  
May we always show loving care to those around us,  
especially those in most need.  
We ask this through Christ our Lord.  
Amen.

### Estimated time

**This lesson:** 10 min [**Total: 46 min** ]{style="float:right" .small}