---
title: Fifth Lesson
subtitle: '**The Birth of Jesus:** *Jesus was born of Mary, who was engaged to Joseph, son of David.* [Matthew 1:18-24]{style="float:right" .small}'
---

## Lesson

A reading from the gospel according to Matthew:

The birth of Jesus the Messiah took place in this way.  
When his mother Mary had been engaged to Joseph,  
but before they lived together,  
she was found to be with child from the Holy Spirit.  

Her husband Joseph, being a righteous man  
and unwilling to expose her to public disgrace,  
planned to dismiss her quietly.  

But just when he had resolved to do this,  
an angel of the Lord appeared to him in a dream and said,  
“Joseph, son of David,  
do not be afraid to take Mary as your wife,  
for the child conceived in her is from the Holy Spirit.  
She will bear a son,  
and you are to name him Jesus,  
for he will save his people from their sins.”  

All this took place  
to fulfil what had been spoken by the Lord through the prophet:  
“Look, the virgin shall conceive and bear a son,  
and they shall name him Emmanuel,”  
which means, “God is with us.”  
When Joseph awoke from sleep,  
he did as the angel of the Lord commanded him;  
he took her as his wife.  

The word of the Lord.

## Carol

#### Mary, Did You Know?[^1] [Mark Lowry and Buddy Greene]{style="float:right" .small}

{{< video https://www.youtube.com/watch?v=F1H1-scfD1s >}}

[^1]: We will need to purchase a version of this from somewhere.

## Prayer


### Estimated time

**This lesson:** 6 min [**Total: 36 min** ]{style="float:right" .small}