---
title: First Lesson
subtitle: '**The Fall of Man:** *God saw everything that he had made, and indeed, it was very good.* [Genesis 3:8-15, 20]{style="float:right" .small}'
---

## Lesson

A reading from the book of Genesis.

After the woman and the man had eaten from the tree,  
they heard the sound of the Lord God walking in the garden  
at the time of the evening breeze,  
and the man and his wife hid themselves from the presence of the Lord God  
among the trees of the garden.  
But the Lord God called to the man, and said to him,  
“Where are you?”  
He said, “I heard the sound of you in the garden,  
and I was afraid, because I was naked; and I hid myself.”  

God said, “Who told you that you were naked?  
Have you eaten from the tree of which I commanded you not to eat?”  

The man said, “The woman whom you gave to be with me,  
she gave me fruit from the tree, and I ate.”  

Then the Lord God said to the woman,  
“What is this that you have done?”  
The woman said, “The serpent tricked me, and I ate.”  

The Lord God said to the serpent,  
“Because you have done this,  
cursed are you among all animals  
and among all wild creatures;  
upon your belly you shall go,  
and dust you shall eat  
all the days of your life.  
I will put enmity between you and the woman,  
and between your offspring and hers;  
he will strike your head,  
and you will strike his heel.”  

The man gave his wife the name “Eve,”  
because she was the mother of all the living.

The word of the Lord.

## Carol

#### Night of Silence / Silent Night [Daniel Kantor]{style="float:right" .small}

{{< video https://www.youtube.com/watch?v=PMVgMmj2Sio >}}

Arrangement options:
- Adults sing "Night of Silence", kids hum (ooo's) "Silent Night" under last verse
- Combination like in recording

## Prayer

Lord of mercy,  
despite our sinfulness,  
you never stopped loving us.  
Fill our hearts with your mercy,  
that we may forgive others.  
We ask this through Christ our Lord.  
Amen.

### Estimated time

**This lesson:** 6 min [**Total: 16 min** ]{style="float:right" .small}