---
title: Introit
---

### Prelude

#### Maranatha, Lord Messiah [Kathy Powell]{style="float:right" .small}

{{< video https://www.youtube.com/watch?v=YQQjF8pTBV4 >}}

Adult choir before service starts?

### Processionals

#### **Children's entrance:** Once In Royal David's City [IRBY]{style="float:right" .small} 

{{< video https://www.youtube.com/watch?v=QmspXB6lUeg >}}

Children process in reverently starting with verse 2.

- Choristers process down middle aisle, turn left, and process to choir area.
- Pageant performers process down middle aisle and into front pews (or wherever they will be seated.)

Try to make this procession slow and reverent as the hymn is sung.  

- Verse 1: Student solo(?) *a capella*  
- Verse 2: Adult choir *a capella*  
- Verse 3: Combined choirs with organ  
- Verse 4: Children's choir with organ  
- Verse 5: Combined choirs with congregation and descant(?) with full organ

#### **Lectors, presider:** O Come, Divine Messiah [VENEZ, DIVIN MESSIE]{style="float:right" .small}

{{< video https://www.youtube.com/watch?v=v1hCHbiEOuY >}}

Book bearer and Presider (others?) process as usual.

Choirs and congregation sing full hymn. Accompanied on piano and/or organ.
